In [ ]:
import numpy as np

# Q2
followers=np.array([1200,15000,67000,340000,1250000])

print(followers)

print("shape :", followers.shape)
print("no_of_dimension :", followers.ndim)
print("data_type :", followers.dtype)

[   1200   15000   67000  340000 1250000]
shape : (5,)
no_of_dimension : 1
data_type : int64


In [2]:
# Q3

arr=np.arange(101,111)
print(arr,"\n size_of_arr :",arr.size)


[101 102 103 104 105 106 107 108 109 110] 
 size_of_arr : 10


In [3]:
# Q4

matrix=np.eye(3)

print(matrix)

# The diagonal values (1s) represent a playlist matching itself,
# meaning each playlist has a perfect similarity/like score with itself.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Q5

# Python list of cricket scores
scores = [45, 67, 120, 89, 54]

# Convert list to NumPy array
scores_array = np.array(scores)

# Print the array
print("Cricket Scores:", scores_array)

# Print memory used by each element
print("Bytes per score:", scores_array.itemsize)

Cricket Scores: [ 45  67 120  89  54]
Bytes per score: 8
