In [ ]:
import numpy as np

# Q1
# Daily step counts of two friends for 7 days
friend1 = np.array([8000, 10000, 7500, 9000, 12000, 11000, 9500])
friend2 = np.array([7000, 9500, 8000, 8500, 10000, 10500, 9000])


addition = friend1 + friend2

subtraction = friend1 - friend2


multiplication = friend1 * friend2


division = friend1 / friend2

print("Friend 1 Steps:", friend1)
print("Friend 2 Steps:", friend2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

print("\nDivision:")
print(division)

Friend 1 Steps: [ 8000 10000  7500  9000 12000 11000  9500]
Friend 2 Steps: [ 7000  9500  8000  8500 10000 10500  9000]

Addition:
[15000 19500 15500 17500 22000 21500 18500]

Subtraction:
[1000  500 -500  500 2000  500  500]

Multiplication:
[ 56000000  95000000  60000000  76500000 120000000 115500000  85500000]

Division:
[1.14285714 1.05263158 0.9375     1.05882353 1.2        1.04761905
 1.05555556]


In [2]:
# Q2
friend1=np.array([3,4,5,
                2,4,1,
                7,6,8])

friend2=np.array([4,3,5,
                2,7,1,
                7,6,1])

dot_result = np.dot(friend1, friend2)

# Matrix multiplication
matmul_result = np.matmul(friend1, friend2)

print("Dot Product:", dot_result)
print("Matmul Result:", matmul_result)

Dot Product: 175
Matmul Result: 175


In [3]:
# Q3
matrix=np.array([3,4,5,4,
                2,4,1,6,
                7,6,8,7,
                4,3,2,1]).reshape((4,4))

transposed_matrix=np.transpose(matrix)
print(transposed_matrix)

print("mean :",np.mean(matrix))
print("standard deviation : ",np.std(matrix))
print("variance : ",np.var(matrix))

[[3 2 7 4]
 [4 4 6 3]
 [5 1 8 2]
 [4 6 7 1]]
mean : 4.1875
standard deviation :  2.098176291449315
variance :  4.40234375


In [4]:
# Q4
A = np.array([[4, 2],
              [1, 3]])

print("Matrix:",A)


print("Determinant:",np.linalg.det(A))

print("Inverse:",np.linalg.inv(A))


eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:",eigenvalues)

print("Eigenvectors:",eigenvectors)

Matrix: [[4 2]
 [1 3]]
Determinant: 10.000000000000002
Inverse: [[ 0.3 -0.2]
 [-0.1  0.4]]
Eigenvalues: [5. 2.]
Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [5]:
# Q5

matrix=np.arange(1,13).reshape(3,4)
print(matrix)

f=matrix.flatten()
print("after flatten",f)
s=np.split(f,2)
print("after splitting in two equal parts :",s)
print("after vstack :",np.vstack((s)))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
after flatten [ 1  2  3  4  5  6  7  8  9 10 11 12]
after splitting in two equal parts : [array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]
after vstack : [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
