In [1]:
# Q1
import numpy as np

ratings = np.array([
    [5, 4, 3, 5, 2],  # User 1
    [4, 5, 4, 3, 5],  # User 2
    [3, 4, 5, 4, 4],  # User 3
    [5, 3, 4, 5, 3]   # User 4
])

print("rating by second customer", ratings[1:3])

rating by second customer [[4 5 4 3 5]
 [3 4 5 4 4]]


In [ ]:
# Q2
steps=np.array([7500,8200,3200,9300,4500,6700,8300,5400,9400,1000])

print("days where steps is greater than 8000",steps > 8000)

days where steps is greater than 8000 [False  True False  True False False  True False  True False]


In [3]:
# Q3
score=np.array([200,190,180,210,170,187,167,233,209,198])

print(score[1:8:3])

[190 170 233]


In [4]:
# Q4
prd_price=np.array([10000,12000,2000,3000,4000])

arr=np.array([prd_price/100*10]).astype(int)

print(arr)

[[1000 1200  200  300  400]]


In [5]:
#Q5
ratings=np.array([-4,2,-3,6,7,0])
d=ratings[ratings<0]=0
print(ratings)

[0 2 0 6 7 0]
